import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components/Icon';

export function EvidenceNew() {
  const [form, setForm] = useState({ title: '', category: '', description: '' }); const [file, setFile] = useState(null); const [errors, setErrors] = useState({}); const [checked, setChecked] = useState(false);
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value })); const checkFields = event => { event.preventDefault(); const next = {}; if (!form.title.trim()) next.title = 'Enter an evidence title.'; if (!form.category) next.category = 'Select an evidence category.'; setErrors(next); setChecked(true); };
  return <div className="dashboard form-page"><div className="form-page-heading"><div><p className="eyebrow">EVIDENCE</p><h1>Add Evidence</h1><p className="page-subtitle">Prototype layout for a future evidence workflow.</p></div><Link className="back-to-cases" to="/case-workspace/evidence"><Icon name="chevronLeft" size={16} />Back to Evidence</Link></div><form className="panel form-panel" onSubmit={checkFields} noValidate><div className="panel-heading"><h2>Evidence details</h2><p>Case association is unavailable until a real case is selected. The selected file remains local and is not uploaded.</p></div><div className="form-fields"><label>Display name<input name="title" value={form.title} onChange={update} aria-invalid={Boolean(errors.title)} />{errors.title && <span className="field-error">{errors.title}</span>}</label><label>Category<select name="category" value={form.category} onChange={update} aria-invalid={Boolean(errors.category)}><option value="">Select a category</option><option>Images</option><option>Video</option><option>Audio</option><option>Digital Evidence</option><option>Other Evidence</option></select>{errors.category && <span className="field-error">{errors.category}</span>}</label><label>Description <span className="optional-label">(optional)</span><textarea name="description" value={form.description} onChange={update} rows="5" /></label><label>Local file <span className="optional-label">(optional)</span><input type="file" onChange={event => setFile(event.target.files?.[0] || null)} /><span className="field-help">No file contents are read, hashed, encrypted, previewed, or persisted.</span>{file && <span className="local-file">Selected locally: {file.name} ({Math.round(file.size / 1024)} KB)</span>}</label></div><div className="form-actions"><button className="check-fields-btn" type="submit"><Icon name="checklist" size={16} />Check fields</button><Link className="cancel-link" to="/case-workspace/evidence">Cancel</Link><button className="disabled-submit" disabled>Add evidence</button></div>{checked && <p className={`validation-message ${Object.keys(errors).length ? 'has-errors' : ''}`} role="status">{Object.keys(errors).length ? 'Check the highlighted fields.' : 'Fields are valid locally. Evidence upload is unavailable.'}</p>}</form></div>;
}
